return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 23,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 30,
  properties = {
    ["water"] = true
  },
  tilesets = {
    {
      name = "spritesheet",
      firstgid = 1,
      filename = "../tilesets/spritesheet.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../gfx/spritesheet.png",
      imagewidth = 2048,
      imageheight = 3456,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 6912,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Background",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0ldSAlEQBdDRhSBJQcKWwEQwsCWigoJuyYQoIOzBswWgZuRjXtX5vFXdt18lCIIqZ5xzwSVX1KjToMk1N9xyR4tKyPk2Hbr06DPgngeGjHjkiTETnnmJIB/2/nF/cX9xf3F/cX/b5fd9vn2/7ytvvPPBJ1O+mPHND3MWLPllxTqCfOIgCI5IkiJNhizHnJAjzykFipQoH4Sfr1DljHMuuOSKGnUaNLnmhlvuaEWQb9OhS48+A+55YMiIR54YM+GZlwjyr7zxzgefTPlixjc/zFmw5JcV6wjyiUP3J0mKNBmyHHNCjjynFChSonwYfn6Tt+stt9llk7frLcOe7z/+wr7P9wcIZqts"
    },
    {
      type = "tilelayer",
      name = "Background2",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgF9AQ3mbCLXweK38AhR0+gxc/AoI0D6/APtOsGJ9AkIVyu4ojjW4M87kd6GmBiYWBgBmIWIGYF4muDIL5gAFe8jdS4GgWDA5BSLpILkNM7vYA7C/FqaeW2C3jkSAl3YtynRUZZIsBImnpcANl9sDYSsWUvEyumWIEQJqYEZAsRj7HZjW7/qPtG3Udv911kRmBC8qRiANdFWgE="
    },
    {
      type = "tilelayer",
      name = "Background3",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzLEJAAAIBLEH9x/OjRzBwkpI4NpLAAAA+KDr3va7GEK2Ejk="
    },
    {
      type = "tilelayer",
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["collidable"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFowABZHjx41GACYgNl8mMhNVMIkINrQChuB9NA8SDq3SMR3Li6twApjNiwKj7KAODwX3Y0p8kCyqm2A4eKKZSuUQNN2ED2vzUMYcY95ETFvjcR0q5P9DhN5FAuqd2fSbNDcHE1p2j9ekoGEkAAJshEAw="
    },
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 317,
          y = 714.667,
          width = 487,
          height = 21.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 804,
          y = 715.333,
          width = 480,
          height = 22.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "vertical_platform",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 544,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "blocker",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 416,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 929.333,
          y = 448,
          width = 26.6667,
          height = 29.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "level_end",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
