return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 23,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 17,
  properties = {
    ["snow"] = true
  },
  tilesets = {
    {
      name = "spritesheet",
      firstgid = 1,
      filename = "../tilesets/spritesheet.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../gfx/spritesheet.png",
      imagewidth = 2048,
      imageheight = 3456,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 6912,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Background",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0VtSgQEAhuE/CxFRiLZEBznbElJ0YksIlUP20LOCzNT4u/kvnst35pv5ikEQFCORSCQS+YUSl1xxzQ1lbqlQpUadBk1atEPoO3TpcUefex4YMOSRJ5554ZUR4xD6CVNmvDFnwZJ3PvhkxZoNW77YhdDHj4LgmARJTkiR5pQzMmTJcU6eAhdHh++LlLjkimtuKHNLhSo16jRo0qIdQt+hS487+tzzwIAhjzzxzAuvjBiH0E+YMuONOQuWvPPBJyvWbNjyxS6EPh7zPwmSnJAizSlnZMiS45w8BS5ih++jf3/u9+3773/37Yv+/du/34zlu1Q="
    },
    {
      type = "tilelayer",
      name = "Background2",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSigDGhxMzBoQ7EON3ZxfBhZz1AFFwbaAQSAAONAuwATFHBjYnSgNYBphBj3DSQYKe7L5iUNU9t9q3kx8aj7cLsPAKwqLY8="
    },
    {
      type = "tilelayer",
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["collidable"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAT1AHxMED2ZArvuEhFExLnF8mJbuoxcYdR9pAD0NcPLgVzMKaANISRe0SEPoZqLzSSlHaJFO6GHHcAIA89MLWQ=="
    },
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "blocker",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 384,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 576,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 608,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 576,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "switch",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "box",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 369,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["stopped"] = true
          }
        },
        {
          id = 13,
          name = "level_end",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 729.333,
          width = 576,
          height = 6.66667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = -2.66667,
          y = 725.333,
          width = 494.667,
          height = 13.3333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
