return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 23,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 24,
  properties = {},
  tilesets = {
    {
      name = "spritesheet",
      firstgid = 1,
      filename = "../tilesets/spritesheet.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../gfx/spritesheet.png",
      imagewidth = 2048,
      imageheight = 3456,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 6912,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Background",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0cVRQ1EAQNGXFBLinpbg4xCgJdylpbhLD5wm8mdg3uIs7+omIYQkiqIoiqLoD+nRZ8CQEWMmTJkxZ8GSFWs2bFPoc5kQ9shToEiJMhWq1KjToEmLNp3M7vt9Dkg45IhjTjjljHMuuKTLFdfcpNDfcsc9DzzyxDMvvPLGOx988sU3Pyn0PfoMGDJizIQpM+YsWLJizYZtCn0u6z95ChQpUaZClRp1GjRp0aaT3X0f//7vv7/ceJM8"
    },
    {
      type = "tilelayer",
      name = "Background2",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJwAOwvpmJ7AhJ+BwZREbMZPXzcORjCdiYFhBhOm+Ew0sQhGCD0Vi1pagYGI0wvUcTrJwJhIdwsw0tYdlIKRkLdMRoAfhzqAlWvTyCyvZjFhloHkmoUMtgpSH5cSiQm6jX9g3UeoPQFyHwBFXT3o"
    },
    {
      type = "tilelayer",
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["collidable"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLBJEb62SXESx4mFUxgRsWDGQx29xEC9IrTwQCGqrvRwWCPh1J+TDFYPiE2T9PSj9jcN5jAUHdfP4E6iZA8LjCRSH3klmnUwMS4bbADAG/mEQs="
    },
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 608,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "box_block",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "spring",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "box_block",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "spring",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 512,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 682.667,
          y = 725.333,
          width = 600,
          height = 13.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "spring",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "snail",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "spike",
          type = "",
          shape = "rectangle",
          x = 453.333,
          y = 310.667,
          width = 406.667,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "box_block",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 256,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["stopped"] = true
          }
        },
        {
          id = 19,
          name = "switch",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "blocker",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 384,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "vert_platform",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["stopped"] = true
          }
        },
        {
          id = 22,
          name = "blob",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "level_end",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
